### PR TITLE
Add SVG format figures; fix usage of deprecated constants in wait

### PR DESCRIPTION
**Pull request by manjugv**
https://github.com/openshmem-org/specification/issues/179

### CODE REVIEW

**Comment by naveen-rn** [comment]
changes look fine with me - @davidozog, @nspark and @BryantLam can i get approvals from the section committee?

**Comment by davidozog** [comment]
@manjugv - perhaps I'm missing something, but I still see the `_` prefix on the "wait" diagram.  Is this because the Latex should be using `wait_v2`?

I also might see other missing updates (`long_fadd` -> `long_atomic_fadd`) but I'm unfamiliar with this issue(s).  Perhaps @jamesaross could have a look?

**Comment by manjugv** [comment]
@davidozog You are right. This PR is just adding the diagram to the repo. Also, adding the SVG format (open format) to address other issues.

I have not updated the text. But, I can update it if needed. If we are OK with the wait_v2 figure, we can delete the older version and rename wait_v2 ->wait.

I'm not familiar with long_fadd -> long_atomic_fadd issues either. However, @jamesaross can update it easily now.

**Comment by manjugv** [comment]
@davidozog With the new commit, the wait diagram changes should be reflected in the pdf. I moved the legacy files under wait_v1_4.* naming.

**Comment by naveen-rn** [comment]
@manjugv  I have pulled in all the required changes into the PR #8 and updated the diagram to fit in the specification after changing the fadd APIs. Closing this PR for now.

**Comment by manjugv** [comment]
Thanks! @naveen-rn

**Pull request closed without merging**
