### PR TITLE
RM data types from memory ordering figures

### PR DESCRIPTION
**Pull request by naveen-rn**
The figures in the memory ordering section had datatypes in the
OpenSHMEM routines. Removing them and using C11 routines.

Another important change in the figure is that:
- previously we used shmem_int_p in the wait_until figure, changing
that to shmem_atomic_set

We have also removed the barrier image from the MO section.

This PR fixes issue https://github.com/openshmem-org/specification/issues/406 and https://github.com/openshmem-org/specification/issues/407, https://github.com/openshmem-org/specification/issues/408

### CODE REVIEW

**Comment by naveen-rn** [comment]
@nspark https://github.com/BryantLam @bryantLam Some quick review for the changes to the figure.

**Comment by nspark** [comment]
@naveen-rn Some of the text spacing seems off, in particular around boldface words:

odd-word-spacing

**Comment by naveen-rn** [comment]
image
Fixed.

**Review by nspark — APPROVED** [review]

**Comment by BryantLam** [comment]
@naveen-rn -- ~~Rather than removing the `shmem_barrier` example, I would prefer deprecate markers around it until it can be replaced with a teams-based example.~~ Disregard. I didn't see that this concern was handled by https://github.com/naveen-rn/specification/pull/18.

**Comment by BryantLam** [comment]
Also minor note: `shmem_barrier_all` example has "`shmem_barrier_all(...)`", but the function doesn't take any arguments.

**Comment by BryantLam** [comment]
Nitpick: First figure (p2p sync with `shmem_wait_until`) is missing a space after the addr-comma in the middle-top block: `shmem_wait_until(addr,SHMEM_CMP_EQ, value)`

**Comment by naveen-rn** [comment]
@BryantLam Fixed both the barrierall and wait spacing and (...) issues.

**Pull request merged**
